import type { Metadata } from "next";
import { Lato, Kanit } from "next/font/google";
import "./globals.css";

const lato = Lato({
   subsets: ['latin'],
   weight: ['400','700'],
   style: ['normal','italic'],
   variable: '--font-lato',
});
const kanit = Kanit({ 
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-kanit',});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${kanit.variable} ${lato.variable}`}>{children}</body>
    </html>
  );
}
